# Mean and Standard Deviation Calculator
The project calculates the mean an standard deviation of a set of n real numbers.
In here the use of a linked list is required thus a custom linked list is implemented.
GitFlow was used to maintain a well organized workflow within a Git repository. 

## Badges

To see this project deployed in Heroku [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://blooming-ridge-55856.herokuapp.com/inputdata)

Continous Integration [![CircleCI](https://circleci.com/gh/circleci/circleci-docs.svg?style=svg)](https://circleci.com/gh/srubianof/AREP-LAB-2)
## Getting Started
The following steps are required in order to get a copy of the project, be able to run it and perform tests.
### Prerequisites
You need to have installed the next software to successfully run the project:

* Java recommended Java 8
* Maven
* Git
### Installing
This a step by step guide that will tell you how to get a copy of the project and how to execute
        
First get a copy of the repository
```
git clone https://github.com/srubianof/AREP-LAB-1.git
```
Once the project is downloaded in your machine, you can build it with the next command
```
mvn package
```

## Test execution
 In order to run the test you have to keep in mind that you must have downloaded the repository and have opened a new terminal in the project folder.
 
 To execute the tests you have to type the following command:
 
 ```
mvn test
```
## Program execution
Before you run the program please keep in mind that this program needs the name of the file where the set of numbers are located including the extension.

For a proper execution of the project type in the terminal the following command:

```
java -cp target/ComplexSystems-1.0-SNAPSHOT.jar edu.escuelaing.arem.ComplexSystems.App "data.txt"

```

## Built With
* Java 8
* Git - Version-control system
* [Maven](https://maven.apache.org) - Dependency Management
## Javadoc

The complete documentation of the project can be found [here](https://srubianof.github.io/ComplexSystems.github.io/).

The complete report of the activity can be found [here](https://github.com/srubianof/AREP-LAB-2/blob/master/AREP_LAB_2.pdf)

The following document provides an overview of the various documents and links that are part of this project's general information. All of this content is automatically generated by Maven on behalf of the project. The documentation can be found [here](https://srubianof.github.io/ComplexSystemsMvn.github.io/).

In order to generate the documentation type the following commands in the terminal:
* This generates a html with the javadoc
```
mvn javadoc:javadoc
```
* This generates a site for the project where the project's reports are included.
```
mvn site
```
* This opens the site where the documentation is located
```
mvn site:run
```


## Versioning

We use GitFlow for versioning. For the versions available, see the [tags on this repository](https://github.com/srubianof/AREP-LAB-1/releases).

## Author

[**Santiago Rubiano Fierro**](https://github.com/srubianof) Software Engineering Student

## License

 This project is licensed under the MIT License - see the [LICENSE.md](https://github.com/srubianof/AREP-LAB-1/blob/master/LICENSE) file for details.